### ISSUE TITLE
Instructions for installing subnet-cli seem incomplete

### ISSUE THREAD

**Issue by tvongerlach** [ava-labs/subnet-cli#17]
I followed the steps  outlined in the `README.md` and after running `go install -v .` and it seemingly downloading everything successfully I still get `zsh: command not found: subnet-cli`. 

I followed the steps [here](https://stackoverflow.com/questions/25216765/gobin-not-set-cannot-run-go-install) to set my GOBIN path unfortunately without success. 

Any pointers would be much appreciated. Thanks

**Comment by hexfusion** [comment]
what is the output of these commands.
```
$ go env GOPATH
$ echo $PATH
```

**Comment by tvongerlach** [comment]
```
➜  .oh-my-zsh git:(master) go env GOPATH
/Users/tassilovongerlach/go
➜  .oh-my-zsh git:(master) echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin
➜  .oh-my-zsh git:(master)
```

**Comment by hexfusion** [comment]
The bin is not in your path and is most likely $GOPATH/bin as per golang docs.
```
/Users/tassilovongerlach/go/bin
```
The docs seem clear. HTH

**Comment by tassivg** [comment]
Thanks for the pointer. It works now

**Comment by tvongerlach** [comment]
Thanks for pointing me in the right direction. I fixed it

**Comment by derricktan33** [comment]
mkdir -p $HOME/go/bin
echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.profile
echo "export PATH=$PATH:$(go env GOPATH)/bin" >> ~/.profile
source ~/.profile

Setting environment variables:
solved my issue
