### ISSUE TITLE
Error while creating new avalanche vm error during vm's Initialize: unknown codec version

### ISSUE THREAD

**Issue by metmirr** [ava-labs/subnet-cli#27]
Hi, I have a local testnet running based on this tutorial https://docs.avax.network/build/tutorials/platform/create-a-local-test-network. And Genesis file `fake-genesis.json` has the same content as here https://docs.avax.network/build/tutorials/platform/subnets/create-avm-blockchain#create-the-genesis-data.

- OS: Ubuntu 20.04 
- Avalanche: avalanche/1.7.4 [database=v1.4.5, commit=e388a890b6c02c0f58fd116357fe508e65bb1c42]

I am using subnet-cli wizard to create a subnet and an avm blockchain:

```shell
subnet-cli wizard --node-ids=NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg,NodeID-MFrZFVCXPv5iCn6M9K6XduxGTYp891xXZ,NodeID-NFBbbJ4qCmNaCzeW7sxErhvWqvEQMnYcN,NodeID-GWPcbFJZFfZreETSoWjPimr846mXEKCtu,NodeID-P7oB2McjBGgW2NXXWVYjV8JEDFoW9xDE5 --public-uri=http://127.0.0.1:9650 --vm-genesis-path=fake-genesis.json --vm-id=jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq --chain-name=mychain --private-key-path=./.insecure.ewoq.key
```
This is the subnet-cli output everything seems fine:

![Screen Shot 2022-03-14 at 6 40 38 PM](https://user-images.githubusercontent.com/11671753/158219571-a37dea1e-ab97-416c-8574-2550cfb3de0c.png)

But all the validator nodes(5) are showing this error:
```shell
ERROR[03-14|16:38:46] chains/manager.go#270: error creating chain 2TxnUundHxxjDGeN4rYJpGKxCPJkUEDMQgL5ewmpKPdsnFN1MZ: error while creating new avalanche vm error during vm's Initialize: unknown codec version
```
![Screen Shot 2022-03-14 at 6 44 11 PM](https://user-images.githubusercontent.com/11671753/158219977-b41ed75b-d619-4afe-a7fd-b0fbf942574f.png)

**Comment by chaddwick25** [comment]
Try this file instead https://docs.avax.network/build/tutorials/platform/subnets/create-evm-blockchain/#create-the-genesis-data
