### ISSUE TITLE
SubnetCLI generates hex key and expects cb58 format

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-cli#33]
The subnet-cli command `subnet-cli create key` generates a key in hex format as expected by MM, but then it expects the private key that it uses for other interactions to be in the `PrivateKey-<CB58 string>` format. We should fix this so that it either generates a private key in the expected format for interaction with the subnet-cli or allow the subnet-cli to read in both formats.

**Comment by aaronbuchwald** [comment]
![image](https://user-images.githubusercontent.com/24684335/167882183-a83b564a-1f0a-4e95-9873-4d1bbda474ce.png)

```
subnet-cli wizard --node-ids=NodeID-Gk9hqRt51oKinFJwxDPFj34akC5Aa54op --vm-genesis-path=networks/11111/genesis.json --vm-id=srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy --chain-name=subnetevm

i got error "invalid private key length (expect 64 bytes in hex)". 
It surely seems that the tool expects the private key in hex format which we have already tried.
```

**Comment by moreshk** [comment]
Hi, when will this be deployed

**Comment by akshaysrivastav** [comment]
Still facing this issue. Mentioning the details below.

Platform details:
- OS - Ubuntu 20.04.4 LTS
- Go version - go1.18.1 linux/amd64
- Subnet-cli version - 0.0.3 (commit hash fe9e0dc22afeeae73b6019beb9e7355ee1d47af0)

Steps to reproduce
1. git clone https://github.com/ava-labs/subnet-cli.git;
2. cd subnet-cli;
3. go install -v .;
4. go/bin/subnet-cli create key

The `create` command generates a private key in hex format. Here is the generated key `eab41ec52f9c7757cd3d7ba894f022253c9d480ff2224b882b687c6f18de8d19`
